import { describe, expect, it } from 'vitest';

import type {
  AuditLedger,
  Checkpoint,
  Decision,
  EvidenceReference,
  TestExecution,
  TestPlanVersion,
} from '../src/domain/work-item-audit.js';
import { AuditProjectionService } from '../src/services/audit-projection-service.js';

function emptyLedger(overrides: Partial<AuditLedger> = {}): AuditLedger {
  return {
    schemaVersion: '1.0.0',
    revision: 0,
    updatedAt: '2026-07-24T10:00:00.000Z',
    decisions: [],
    checkpoints: [],
    testPlans: [],
    testExecutions: [],
    evidenceReferences: [],
    idempotencyIndex: [],
    ...overrides,
  };
}

function decision(overrides: Partial<Decision> = {}): Decision {
  return {
    id: 'decision-1',
    idempotencyKey: 'decision-key-1',
    kind: 'DECISION',
    title: 'Select a local ledger',
    decision: 'Use one structured ledger.',
    rationale: 'It provides deterministic validation.',
    declaredActor: 'Architecture reviewer',
    recordedAt: '2026-07-24T10:00:00.000Z',
    ...overrides,
  };
}

function checkpoint(overrides: Partial<Checkpoint> = {}): Checkpoint {
  return {
    id: 'checkpoint-1',
    idempotencyKey: 'checkpoint-key-1',
    kind: 'PROGRESS',
    summary: 'Domain contracts implemented.',
    declaredActor: 'Delivery lead',
    recordedAt: '2026-07-24T11:00:00.000Z',
    ...overrides,
  };
}

function evidence(overrides: Partial<EvidenceReference> = {}): EvidenceReference {
  return {
    id: 'evidence-1',
    idempotencyKey: 'evidence-key-1',
    label: 'Automated test report',
    description: 'Report generated by the local test command.',
    logicalPath: 'evidence/test-report.txt',
    declaredActor: 'Test operator',
    recordedAt: '2026-07-24T12:00:00.000Z',
    ...overrides,
  };
}

function plansAndExecutions(): {
  plans: TestPlanVersion[];
  executions: TestExecution[];
} {
  return {
    plans: [
      {
        id: 'plan-version-1',
        planId: 'plan-1',
        planRevision: 1,
        idempotencyKey: 'plan-key-1',
        purpose: 'Validate the initial implementation.',
        declaredActor: 'Test lead',
        recordedAt: '2026-07-24T10:00:00.000Z',
        testCases: [
          {
            testCaseId: 'case-old',
            title: 'Historical case',
            objective: 'Validate revision one.',
            verificationMethod: 'MANUAL',
            expectedOutcome: 'Revision one behaves correctly.',
          },
        ],
      },
      {
        id: 'plan-version-2',
        planId: 'plan-1',
        planRevision: 2,
        idempotencyKey: 'plan-key-2',
        purpose: 'Validate the active implementation.',
        declaredActor: 'Test lead',
        recordedAt: '2026-07-24T11:00:00.000Z',
        testCases: [
          {
            testCaseId: 'case-b',
            title: 'B case',
            objective: 'Validate the second behavior.',
            verificationMethod: 'AUTOMATED',
            expectedOutcome: 'The second behavior passes.',
          },
          {
            testCaseId: 'case-a',
            title: 'A case',
            objective: 'Validate the first behavior.',
            verificationMethod: 'MANUAL',
            expectedOutcome: 'The first behavior passes.',
          },
        ],
      },
    ],
    executions: [
      {
        id: 'execution-historical',
        idempotencyKey: 'execution-key-historical',
        planId: 'plan-1',
        planRevision: 1,
        testCaseId: 'case-old',
        executionMethod: 'MANUAL',
        outcome: 'PASSED',
        summary: 'Historical revision passed.',
        declaredActor: 'Tester',
        recordedAt: '2026-07-24T10:30:00.000Z',
      },
      {
        id: 'execution-active-old',
        idempotencyKey: 'execution-key-active-old',
        planId: 'plan-1',
        planRevision: 2,
        testCaseId: 'case-a',
        executionMethod: 'MANUAL',
        outcome: 'FAILED',
        summary: 'The first attempt failed.',
        declaredActor: 'Tester',
        recordedAt: '2026-07-24T12:00:00.000Z',
      },
      {
        id: 'execution-active-new',
        idempotencyKey: 'execution-key-active-new',
        planId: 'plan-1',
        planRevision: 2,
        testCaseId: 'case-a',
        executionMethod: 'MANUAL',
        outcome: 'PASSED',
        summary: 'The corrected attempt passed.',
        declaredActor: 'Tester',
        recordedAt: '2026-07-24T13:00:00.000Z',
      },
    ],
  };
}

describe('AuditProjectionService', () => {
  it('renders four protected deterministic empty projections', () => {
    const service = new AuditProjectionService();
    const ledger = emptyLedger();

    const first = service.project(ledger);
    const second = service.project(ledger);

    expect(first).toEqual(second);
    expect(Object.values(first)).toHaveLength(4);
    for (const projection of Object.values(first)) {
      expect(projection).toContain('DO NOT EDIT DIRECTLY');
      expect(projection).toContain('structured audit ledger is the authoritative record');
      expect(projection.endsWith('\n')).toBe(true);
    }
    expect(first.decisions).toContain('_No decision entries recorded._');
    expect(first.checkpoints).toContain('_No checkpoint entries recorded._');
    expect(first.testPlan).toContain('_No test plan has been defined._');
    expect(first.evidenceReferences).toContain('_No evidence references registered._');
  });

  it('derives current decisions while preserving append-only history in stable order', () => {
    const original = decision({
      id: 'decision-original',
      title: 'Original decision',
      recordedAt: '2026-07-24T10:00:00.000Z',
    });
    const superseding = decision({
      id: 'decision-new',
      idempotencyKey: 'decision-key-new',
      kind: 'SUPERSESSION',
      title: 'Replacement decision',
      decision: 'Use the replacement.',
      relatedDecisionId: original.id,
      recordedAt: '2026-07-24T11:00:00.000Z',
    });
    const correction = decision({
      id: 'decision-correction',
      idempotencyKey: 'decision-key-correction',
      kind: 'CORRECTION',
      title: 'Correction of original decision',
      relatedDecisionId: original.id,
      recordedAt: '2026-07-24T10:30:00.000Z',
    });
    const service = new AuditProjectionService();

    const projection = service.projectDecisions(
      emptyLedger({ revision: 3, decisions: [superseding, correction, original] }),
    );
    const [current, history] = projection.split('## Append-only decision history');

    expect(current).toContain('Replacement decision');
    expect(current).not.toContain('Original decision');
    expect(current).not.toContain('Correction of original decision');
    expect(history).toContain('Original decision');
    expect(history).toContain('SUPERSEDED');
    expect(history).toContain('HISTORICAL_RELATED_ENTRY');
    expect(history!.indexOf('Original decision')).toBeLessThan(
      history!.indexOf('Replacement decision'),
    );
  });

  it('marks corrected checkpoints without modifying their historical records', () => {
    const original = checkpoint({
      id: 'checkpoint-original',
      summary: 'Initial status was incomplete.',
    });
    const correction = checkpoint({
      id: 'checkpoint-correction',
      idempotencyKey: 'checkpoint-key-correction',
      summary: 'Initial status is now complete.',
      correctsCheckpointId: original.id,
      recordedAt: '2026-07-24T12:00:00.000Z',
    });
    const service = new AuditProjectionService();

    const projection = service.projectCheckpoints(
      emptyLedger({ revision: 2, checkpoints: [correction, original] }),
    );
    const [current, history] = projection.split('## Append-only checkpoint history');

    expect(current).toContain('Initial status is now complete.');
    expect(current).not.toContain('Initial status was incomplete.');
    expect(history).toContain('Initial status was incomplete.');
    expect(history).toContain('CORRECTED');
    expect(history).toContain('Corrects checkpoint');
  });

  it('renders immutable plan history and uses the latest execution in the active summary', () => {
    const { plans, executions } = plansAndExecutions();
    const service = new AuditProjectionService();

    const projection = service.projectTesting(
      emptyLedger({ revision: 5, testPlans: plans, testExecutions: executions }),
    );
    const [active, history] = projection.split('## Immutable plan-version history');

    expect(active).toContain('Revision 2');
    expect(active).toContain('execution-active-new');
    expect(active).toContain('PASSED');
    expect(active).not.toContain('execution-active-old');
    expect(active!.indexOf('A case')).toBeLessThan(active!.indexOf('B case'));
    expect(history).toContain('Plan revision 1');
    expect(history).toContain('Plan revision 2');
    expect(history).toContain('Historical revision passed.');
    expect(history).toContain('The first attempt failed.');
    expect(history).toContain('The corrected attempt passed.');
  });

  it('projects evidence metadata without claiming file existence or reading content', () => {
    const service = new AuditProjectionService();
    const reference = evidence();

    const projection = service.projectEvidenceReferences(
      emptyLedger({ revision: 1, evidenceReferences: [reference] }),
    );

    expect(projection).toContain(reference.label);
    expect(projection).toContain(reference.logicalPath);
    expect(projection).toContain('Metadata reference only');
    expect(projection).toContain('file existence and content were not checked');
  });

  it('normalizes multiline user text so it cannot inject projection headings', () => {
    const service = new AuditProjectionService();
    const projection = service.projectDecisions(
      emptyLedger({
        decisions: [
          decision({
            title: 'Decision\n## Injected heading',
            decision: 'Use *literal* supplied text.',
          }),
        ],
      }),
    );

    expect(projection).not.toContain('\n## Injected heading');
    expect(projection).toContain('Decision \\#\\# Injected heading');
    expect(projection).toContain('Use \\*literal\\* supplied text.');
  });
});
